spring.application.name=thymleafDemo

#Countries data
countries=Brazil,France,Argentina,India,USA,Nigeria,Sri-lanka

#FavLang data
favProgLang=Java,Python,Go,CSharp,C

#OS
knownOS=MAC,Linux,Microsoft windows,Android,IOS